server:
  port: 9090
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/static
  application:
    name: cavy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATA_SOURCE_URL:jdbc:mysql://127.0.0.1:3306/cavy?characterEncoding=utf8}
    username: ${DATA_SOURCE_USERNAME:root}
    password: ${DATA_SOURCE_PASSWORD:root}
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema.sql

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

def:
  aes-key: ${DEF_AES_KEY:osuYnpSXHvfTYBtm}
  zip-key: ${DEF_ZIP_KEY:wsaYbpWXXvfFMBes}

task:
  enable:
    backup: true
  cron:
    backup: 0 0/1 * * * ?